name: Issues - Transfer issues
on:
  issues:
    types:
      - labeled
jobs:
  transfer:
    runs-on: docker
    steps:
      - name: Transfer
        uses: lando/transfer-issue-action@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          router: move:firefly-iii
          create_stub: false
